# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
      - /source/App
      - /source/Databricks
      - /source/FeatureManagement
      - /source/JsonSerialization
      - /source/Logging
      - /source/Messaging
      - /source/Outbox
      - /source/TestCommon
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "Microsoft.*"
        versions: ["999.*"]
        