# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
- package-ecosystem: "nuget"
  directory: /source/App
  schedule:
    interval: "weekly"
  ignore:
  - dependency-name: "Microsoft.*"
    versions: [ "999.*" ]

- package-ecosystem: "nuget"
  directory: /source/Databricks
  schedule:
    interval: "weekly"
  ignore:
  - dependency-name: "Microsoft.*"
    versions: [ "999.*" ]

- package-ecosystem: "nuget"
  directory: /source/FeatureManagement
  schedule:
    interval: "weekly"
  ignore:
  - dependency-name: "Microsoft.*"
    versions: [ "999.*" ]

- package-ecosystem: "nuget"
  directory: /source/JsonSerialization
  schedule:
    interval: "weekly"
  ignore:
  - dependency-name: "Microsoft.*"
    versions: [ "999.*" ]

- package-ecosystem: "nuget"
  directory: /source/Logging
  schedule:
    interval: "weekly"
  ignore:
  - dependency-name: "Microsoft.*"
    versions: [ "999.*" ]

- package-ecosystem: "nuget"
  directory: /source/Messaging
  schedule:
    interval: "weekly"
  ignore:
  - dependency-name: "Microsoft.*"
    versions: [ "999.*" ]

- package-ecosystem: "nuget"
  directory: /source/Outbox
  schedule:
    interval: "weekly"
  ignore:
  - dependency-name: "Microsoft.*"
    versions: [ "999.*" ]

- package-ecosystem: "nuget"
  directory: /source/TestCommon
  schedule:
    interval: "weekly"
  ignore:
  - dependency-name: "Microsoft.*"
    versions: [ "999.*" ]
