# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
- package-ecosystem: "nuget"
  directory: /source/App
  schedule:
    interval: "weekly"
  groups:
    app-package-minor-and-patch:
      applies-to: version-updates
      update-types:
      - minor
      - patch
    app-package-security:
      applies-to: security-updates
      patterns:
      - "*" # Applies to all security updates
  ignore:
  - dependency-name: "Microsoft.*"
    versions: [ "999.*" ]

- package-ecosystem: "nuget"
  directory: /source/Databricks
  schedule:
    interval: "weekly"
  groups:
    databricks-package-minor-and-patch:
      applies-to: version-updates
      update-types:
      - minor
      - patch
    databricks-package-security:
      applies-to: security-updates
      patterns:
      - "*" # Applies to all security updates
  ignore:
  - dependency-name: "Microsoft.*"
    versions: [ "999.*" ]

- package-ecosystem: "nuget"
  directory: /source/FeatureManagement
  schedule:
    interval: "weekly"
  groups:
    feature-management-package-minor-and-patch:
      applies-to: version-updates
      update-types:
      - minor
      - patch
    feature-management-package-security:
      applies-to: security-updates
      patterns:
      - "*" # Applies to all security updates
  ignore:
  - dependency-name: "Microsoft.*"
    versions: [ "999.*" ]

- package-ecosystem: "nuget"
  directory: /source/JsonSerialization
  schedule:
    interval: "weekly"
  groups:
    json-serialization-package-minor-and-patch:
      applies-to: version-updates
      update-types:
      - minor
      - patch
    json-serialization-package-security:
      applies-to: security-updates
      patterns:
      - "*" # Applies to all security updates
  ignore:
  - dependency-name: "Microsoft.*"
    versions: [ "999.*" ]

- package-ecosystem: "nuget"
  directory: /source/Logging
  schedule:
    interval: "weekly"
  groups:
    logging-package-minor-and-patch:
      applies-to: version-updates
      update-types:
      - minor
      - patch
    logging-package-security:
      applies-to: security-updates
      patterns:
      - "*" # Applies to all security updates
  ignore:
  - dependency-name: "Microsoft.*"
    versions: [ "999.*" ]

- package-ecosystem: "nuget"
  directory: /source/Messaging
  schedule:
    interval: "weekly"
  groups:
    messaging-package-minor-and-patch:
      applies-to: version-updates
      update-types:
      - minor
      - patch
    messaging-package-security:
      applies-to: security-updates
      patterns:
      - "*" # Applies to all security updates
  ignore:
  - dependency-name: "Microsoft.*"
    versions: [ "999.*" ]

- package-ecosystem: "nuget"
  directory: /source/Outbox
  schedule:
    interval: "weekly"
  groups:
    outbox-package-minor-and-patch:
      applies-to: version-updates
      update-types:
      - minor
      - patch
    outbox-package-security:
      applies-to: security-updates
      patterns:
      - "*" # Applies to all security updates
  ignore:
  - dependency-name: "Microsoft.*"
    versions: [ "999.*" ]

- package-ecosystem: "nuget"
  directory: /source/TestCommon
  schedule:
    interval: "weekly"
  groups:
    test-common-package-minor-and-patch:
      applies-to: version-updates
      update-types:
      - minor
      - patch
    test-common-package-security:
      applies-to: security-updates
      patterns:
      - "*" # Applies to all security updates
  ignore:
  - dependency-name: "Microsoft.*"
    versions: [ "999.*" ]
