flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true
  individual_flags: # exceptions to the default rules above, stated flag by flag
    - name: appcommon
      paths: 
      - source/App
    - name: jsonserialization
      paths: 
      - source/App