flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true
  individual_flags: # exceptions to the default rules above, stated flag by flag
    - name: appcommon
      paths: 
      - source/App
    - name: logging
      paths: 
      - source/Logging
    - name: messaging
      paths: 
      - source/Messaging
    - name: schemavalidation
      paths: 
      - source/SchemaValidation
    - name: testcommon
      paths: 
      - source/TestCommon
    - name: xmlconversion
      paths: 
      - source/XmlConversion

ignore:
  - "source/FeatureManagement/source/SampleApp.Tests"
  - "source/JsonSerialization/source/JsonSerialization.Tests"
  - "source/Logging/source/RequestResponseMiddleware.Tests"
  - "source/Messaging/source/Messaging.Protobuf.Tests"
  - "source/Messaging/source/Messaging.Tests"
  - "source/SchemaValidation/source/SchemaValidation.Tests"
  - "source/TestCommon/source/FunctionApp.TestCommon.Tests"
  - "source/TestCommon/source/TestCommon.Tests"
  - "source/XmlConversion/source/XmlConverter.Tests"
