# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build and test - fast track

on:
  push:
  # Build, test, pack
  # Executed if Databricks folder or build scripts has changed; including if documentation or tests has changed
  workflow_call: {}
  # Build, test, pack and publish prerelease packages
  # Executed if manually triggered
  workflow_dispatch: {}

env:
  AZURE_KEYVAULT_URL: ${{ vars.integration_test_azure_keyvault_url }}

jobs:
  fast_track:
    runs-on: linux-latest
    name: Build and test - fast track

    environment: AzureAuth

    # We need to have permissions here to be able to support manually triggering this workflow for releasing a pre-release
    permissions:
      id-token: write # Needed by 'dotnet-solution-build-and-test' to login to Azure
      contents: read # Needed by https://github.com/EnricoMi/publish-unit-test-result-action
      issues: read # Needed by https://github.com/EnricoMi/publish-unit-test-result-action
      checks: write # Needed by https://github.com/EnricoMi/publish-unit-test-result-action
      pull-requests: write # Needed by https://github.com/EnricoMi/publish-unit-test-result-action

    steps:
      - name: Login to use Azure resources from automated tests        
        uses: azure/login@v2
        with:
          client-id: ${{ vars.integration_test_azure_spn_id_oidc }}
          tenant-id: ${{ vars.integration_test_azure_tenant_id }}
          subscription-id: ${{ vars.integration_test_azure_subscription_id }}

      - name: Who am i
        run: az account show