# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Publish Json Serialization bundle

on:
  # Build, test, pack and publish release packages
  # Only executed if (*.)JsonSerialization packages content or build scripts has changed; not if solution file, documentation or tests has changed
  push:
    branches:
      - main
    paths:
      - source/JsonSerialization/source/JsonSerialization/**
      - .github/workflows/json-serialization-bundle-publish.yml
  pull_request:
    branches:
      - main
    paths:
      - source/JsonSerialization/**
      - .github/workflows/json-serialization-bundle-publish.yml
  # Build, test, pack and publish prerelease packages
  # Executed if manually triggered
  workflow_dispatch: {}

env:
  # Conditions
  PUSH_PACKAGES: ${{ github.event_name != 'pull_request' }}

jobs:
  build_and_publish:

    # Note: All jobs running in geh-core needs a "CI" environment to pass to ensure that PRs cannot be merged to main before CI has passed
    # Check Branch Protection Rules | "Require deployments to succeed before merging" setting for details
    environment: CI


    runs-on: windows-latest
    name: Publish bundle to NuGet.org

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: Energinet-DataHub/.github/.github/actions/nuget-checkout-repository@7.4.0

      - name: Setup dotnet and tools
        uses: Energinet-DataHub/.github/.github/actions/dotnet-setup-and-tools@7.4.0
        with:
          DOTNET_VERSION: '5.0.407'

      - name: Build and test solution
        uses: Energinet-DataHub/.github/.github/actions/dotnet-solution-build-and-test@7.4.0
        with:
          SOLUTION_FILE_PATH: './source/JsonSerialization/JsonSerialization.sln'
          CODE_COVERAGE_FLAGS: jsonserialization

      - name: Pack JsonSerialization project
        uses: Energinet-DataHub/.github/.github/actions/nuget-project-pack@7.4.0
        with:
          PROJECT_PATH: './source/JsonSerialization/source/JsonSerialization/JsonSerialization.csproj'

      - name: Package content or build has changed
        id: changed-content
        uses: tj-actions/changed-files@v17.2
        with:
          files: |
            source/JsonSerialization/source/JsonSerialization/**/*.*
            .github/workflows/json-serialization-bundle-publish.yml

      - name: Assert versions of NuGet packages and push them to NuGet.org
        uses: Energinet-DataHub/.github/.github/actions/nuget-packages-assert-and-push@7.4.0
        with:
          PUSH_PACKAGES: ${{ env.PUSH_PACKAGES }}
          CONTENT_CHANGED: ${{ steps.changed-content.outputs.any_changed }}
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
          NUPKG_RECURSE_PATH: 'source/JsonSerialization/source'