name: License Check CI

on:
  workflow_call:

jobs:
  check-license-lines:
    name: Check License Lines
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Check License Lines
      uses: kt3k/license_checker@v1.0.3