# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Publish Logging bundle

on:
  # Build, test, pack and publish release packages
  # Only executed if (*.)Logging packages content or build scripts has changed; not if solution file, documentation or tests has changed
  push:
    branches:
      - main
    paths:
      - source/Logging/source/RequestResponseMiddleware/**
      - .github/workflows/logging-bundle-publish.yml
  # Build, test, pack
  # Executed if Validation folder or build scripts has changed; including if documentation or tests has changed
  pull_request:
    branches:
      - main
    paths:
      - source/Logging/**
      - .github/workflows/logging-bundle-publish.yml
  # Build, test, pack and publish prerelease packages
  # Executed if manually triggered
  workflow_dispatch: {}

env:
  # Conditions
  PUSH_PACKAGES: ${{ github.event_name != 'pull_request' }}

jobs:
  build_and_publish:
    runs-on: windows-latest
    name: Publish bundle to NuGet.org

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: Energinet-DataHub/.github/.github/actions/nuget-checkout-repository@7.4.0

      - name: Setup dotnet and tools
        uses: Energinet-DataHub/.github/.github/actions/dotnet-setup-and-tools@7.4.0
        with:
          DOTNET_VERSION: '5.0.407'

      - name: Build and test solution
        uses: Energinet-DataHub/.github/.github/actions/dotnet-solution-build-and-test@7.4.0
        with:
          SOLUTION_FILE_PATH: './source/Logging/Logging.sln'
          CODE_COVERAGE_FLAGS: logging


      - name: Pack RequestResponseMiddleware project
        run: dotnet pack ${{ env.PROJECT_PATH }} --configuration ${{ env.BUILD_CONFIGURATION }} --include-symbols -p:SymbolPackageFormat=snupkg -p:RepositoryCommit=${{ github.sha }} ${{ steps.get_version_suffix.outputs.version_suffix_property }}
        env:
          PROJECT_PATH: "source/Logging/source/RequestResponseMiddleware/RequestResponseMiddleware.csproj"

      - name: Check each NuGet package version does not exists (not looking at prereleases)
        if: ${{ env.PUSH_PACKAGES == 'true' }}
        uses: Energinet-DataHub/.github/.github/actions/nuget-assert-release-version@2.5.0
        with:
          NUPKG_RECURSE_PATH: "source/Logging/source"

      - name: Push to NuGet.org
        if: ${{ env.PUSH_PACKAGES == 'true' }}
        run: dotnet nuget push ${{ env.NUPKG_FILTER_PATTERN }} --api-key ${{ secrets.NUGET_TOKEN }} --source ${{ env.NUGET_FEED_PATH }}
        env:
          NUPKG_FILTER_PATTERN: "source/Logging/source/**/*.nupkg"
          NUGET_FEED_PATH: "https://api.nuget.org/v3/index.json"
