# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Publish Messaging bundle

on:
  # Build, test, pack and publish release packages
  # Only executed if (*.)Messaging packages content or build scripts has changed; not if solution file, documentation or tests has changed
  push:
    branches:
      - main
    paths:
      - source/Messaging/source/Messaging/**
      - source/Messaging/source/Messaging.Integration.ServiceCollection/**
      - source/Messaging/source/Messaging.Protobuf/**
      - source/Messaging/source/Messaging.Protobuf.Integration.ServiceCollection/**
      - .github/workflows/messaging-bundle-publish.yml
  # Build, test, pack
  # Executed if Messaging folder or build scripts has changed; including if documentation or tests has changed
  workflow_call: {}
  # Build, test, pack and publish prerelease packages
  # Executed if manually triggered
  workflow_dispatch: {}

env:
  # Conditions
  PUSH_PACKAGES: ${{ github.event_name != 'pull_request' }}

jobs:
  build_and_publish:
    runs-on: windows-2022
    name: Publish bundle to NuGet.org

    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: Energinet-DataHub/.github/.github/actions/nuget-checkout-repository@v10

      - name: Setup dotnet and tools
        uses: Energinet-DataHub/.github/.github/actions/dotnet-setup-and-tools@v10

      - name: Build and test solution
        uses: Energinet-DataHub/.github/.github/actions/dotnet-solution-build-and-test@v10
        with:
          solution_file_path: ./source/Messaging/Messaging.sln
          code_coverage_flags: messaging
          publish_test_report: "true"

      - name: Pack Messaging project
        uses: Energinet-DataHub/.github/.github/actions/nuget-project-pack@v10
        with:
          project_path: ./source/Messaging/source/Messaging/Messaging.csproj

      - name: Pack Messaging.Integration.ServiceCollection project
        uses: Energinet-DataHub/.github/.github/actions/nuget-project-pack@v10
        with:
          project_path: ./source/Messaging/source/Messaging.Integration.ServiceCollection/Messaging.Integration.ServiceCollection.csproj

      - name: Pack Messaging.Protobuf project
        uses: Energinet-DataHub/.github/.github/actions/nuget-project-pack@v10
        with:
          project_path: ./source/Messaging/source/Messaging.Protobuf/Messaging.Protobuf.csproj

      - name: Pack Messaging.Protobuf.Integration.ServiceCollection project
        uses: Energinet-DataHub/.github/.github/actions/nuget-project-pack@v10
        with:
          project_path: ./source/Messaging/source/Messaging.Protobuf.Integration.ServiceCollection/Messaging.Protobuf.Integration.ServiceCollection.csproj

      - name: Package content or build has changed
        id: changed-content
        uses: tj-actions/changed-files@v35
        with:
          files: |
            source/Messaging/source/Messaging/**/*.*
            source/Messaging/source/Messaging.Integration.ServiceCollection/**/*.*
            source/Messaging/source/Messaging.Protobuf/**/*.*
            source/Messaging/source/Messaging.Protobuf.Integration.ServiceCollection/**/*.*
            .github/workflows/messaging-bundle-publish.yml

      - name: Assert versions of NuGet packages and push them to NuGet.org
        uses: Energinet-DataHub/.github/.github/actions/nuget-packages-assert-and-push@v10
        with:
          push_packages: ${{ env.PUSH_PACKAGES }}
          content_changed: ${{ steps.changed-content.outputs.any_changed }}
          nuget_token: ${{ secrets.nuget_token }}
          nupkg_recurse_path: source/Messaging/source

  #
  # Branch policy status check
  #

  allow_merge:
    runs-on: ubuntu-latest
    needs: [build_and_publish]
    if: |
      always()
    steps:
      - name: Verify if merge is allowed
        run: |
          echo "${{ toJSON(needs) }}"

          if [[ ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }} = true ]]; then
              echo "Failed"
              exit 1
          fi
