# Copyright 2020 Energinet DataHub A/S
#
# Licensed under the Apache License, Version 2.0 (the "License2");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Publish TestCommon bundle

on:
  # Build, test, pack and publish release packages
  # Only executed if (*.)TestCommon packages content or build scripts has changed; not if solution file, documentation or tests has changed
  push:
    branches:
      - main
    paths:
      - source/TestCommon/source/FunctionApp.TestCommon/**
      - source/TestCommon/source/TestCommon/**
      - .github/workflows/testcommon-bundle-publish.yml
  # Build, test, pack
  # Executed if TestCommon folder or build scripts has changed; including if documentation or tests has changed
  pull_request:
    branches:
      - main
    paths:
      - source/TestCommon/**
      - .github/workflows/testcommon-bundle-publish.yml
  # Build, test, pack and publish prerelease packages
  # Executed if manually triggered
  workflow_dispatch: {}

env:
  # Conditions
  PUSH_PACKAGES: ${{ github.event_name != 'pull_request' }}
  # Variables necessary to manage Azure resources for tests (similar to local use of 'integrationtest.local.settings.json')
  AZURE_KEYVAULT_URL: ${{ secrets.AZURE_KEYVAULT_URL }}
  # Set value used by 'AzuriteManager'
  AzuriteBlobFolderPath: '${{ github.workspace }}\node_modules\.bin\'
  # Overrides settings in 'functionhost.settings.json'
  FunctionAppHostPath: '${{ github.workspace }}\node_modules\azure-functions-core-tools\bin\func.dll'

jobs:
  build_and_publish:
    runs-on: windows-2022
    name: Publish bundle to NuGet.org

    permissions:
      contents: read

    environment: CI

    steps:
      - name: Checkout repository (main branch)
        if: ${{ github.ref_name == 'main' }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # To retrieve the preceding commit on 'main'

      - name: Checkout repository (feature branch)
        if: ${{ github.ref_name != 'main' }}
        uses: actions/checkout@v3

      - name: Setup dotnet and tools
        uses: Energinet-DataHub/.github/.github/actions/dotnet-setup-and-tools@7.3.0
        with:
          DOTNET_VERSION: '5.0.407'
          USE_AZURE_FUNCTIONS_TOOLS: 'true'
          NODE_VERSION: '16'
          AZURITE_VERSION: '3.15.0'
          AZURE_FUNCTIONS_CORE_TOOLS_VERSION: '4.0.3971'

      - name: Build and test solution
        uses: Energinet-DataHub/.github/.github/actions/dotnet-solution-build-and-test@7.3.0
        with:
          SOLUTION_FILE_PATH: './source/TestCommon/TestCommon.sln'
          AZURE_KEYVAULT_URL: ${{ secrets.AZURE_KEYVAULT_URL }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_SPN_ID: ${{ secrets.AZURE_SPN_ID }}
          AZURE_SPN_SECRET: ${{ secrets.AZURE_SPN_SECRET }}

      - name: Get version suffix property value
        uses: Energinet-DataHub/.github/.github/actions/get-version-suffix@7.2.1
        id: get_version_suffix

      - name: Pack TestCommon project
        run: dotnet pack ${{ env.PROJECT_PATH }} --configuration ${{ env.BUILD_CONFIGURATION }} --include-symbols -p:SymbolPackageFormat=snupkg -p:RepositoryCommit=${{ github.sha }} ${{ steps.get_version_suffix.outputs.version_suffix_property }}
        env:
          PROJECT_PATH: 'source/TestCommon/source/TestCommon/TestCommon.csproj'

      - name: Pack FunctionApp.TestCommon project
        run: dotnet pack ${{ env.PROJECT_PATH }} --configuration ${{ env.BUILD_CONFIGURATION }} --include-symbols -p:SymbolPackageFormat=snupkg -p:RepositoryCommit=${{ github.sha }} ${{ steps.get_version_suffix.outputs.version_suffix_property }}
        env:
          PROJECT_PATH: 'source/TestCommon/source/FunctionApp.TestCommon/FunctionApp.TestCommon.csproj'

      - name: Package content or build has changed
        id: changed-content
        uses: tj-actions/changed-files@v17.2
        with:
          files: |
            source/TestCommon/source/FunctionApp.TestCommon/**/*.*
            source/TestCommon/source/TestCommon/**/*.*
            .github/workflows/testcommon-bundle-publish.yml

      - name: Check each NuGet package version does not exists (not looking at prereleases)
        if: ${{ env.PUSH_PACKAGES == 'true' || steps.changed-content.outputs.any_changed == 'true'}}
        uses: Energinet-DataHub/.github/.github/actions/nuget-assert-release-version@7.2.1
        with:
          NUPKG_RECURSE_PATH: 'source/TestCommon/source'

      - name: Push to NuGet.org
        if: ${{ env.PUSH_PACKAGES == 'true' }}
        run: dotnet nuget push ${{ env.NUPKG_FILTER_PATTERN }} --api-key ${{ secrets.NUGET_TOKEN }} --source ${{ env.NUGET_FEED_PATH }}
        env:
          NUPKG_FILTER_PATTERN: 'source/TestCommon/source/**/*.nupkg'
          NUGET_FEED_PATH: 'https://api.nuget.org/v3/index.json'
